obj-$(CONFIG_ARCH_MXS)				+= lcdif.o
obj-$(CONFIG_FB_MXS)				+= mxsfb.o
obj-$(CONFIG_FB_MXS_LCD_43WVF1G)		+= lcd_43wvf1g.o
obj-$(CONFIG_FB_MXS_LCD_LMS430)			+= lcd_lms430.o
obj-$(CONFIG_FB_MXS_LCD_AT56)			+= lcd_at56.o
# TVOUT support
obj-$(CONFIG_FB_MXS_TVENC)			+= tvenc.o
